name: CI/CD example

on:
  workflow_dispatch: # Allows you to manually trigger this workflow
  #push:
  #  branches: [ "main" ]

env:
  AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1
  

# Permission can be added at job level or workflow level    
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        role-to-assume: ${{ vars.ACTION_EXECUTE_IAM_ROLE_ARN }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.AWS_REGION }}
        
    # Hello from AWS: WhoAmI
    - name: Sts GetCallerIdentity
      run: |
        aws sts get-caller-identity

    - name: Install agent-evaluation
      run: |
        pip install agent-evaluation
        agenteval --help

    - name: Test Bedrock Agent
      id: test-bedrock-agent
      env:
        BEDROCK_AGENT_ALIAS_ID: ${{ vars.BEDROCK_AGENT_ALIAS_ID }}
        BEDROCK_AGENT_ID: ${{ vars.BEDROCK_AGENT_ID }}
      run: |
        sed -e "s/BEDROCK_AGENT_ALIAS_ID/$BEDROCK_AGENT_ALIAS_ID/g" -e "s/BEDROCK_AGENT_ID/$BEDROCK_AGENT_ID/g" samples/test_plan_templates/bedrock_agent_target/template.yml > agenteval.yml
        agenteval run

    - name: Test Summary
      if: always()
      id: test-summary
      run: |
        if [ -f agenteval_summary.md ]; then
          cat agenteval_summary.md >> $GITHUB_STEP_SUMMARY
        fi
        
