name: Test AWS Bedrock Agent Connectivity

on:
  workflow_dispatch: # Allows you to manually trigger this workflow
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  evaluate-agent:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::438465137422:role/GitHubActionsOIDCRole
        aws-region: us-east-1

    - name: Run Test Command
      run: |
        aws sts get-caller-identity # Verify credentials
        aws bedrock invoke-model \
          --model-id anthropic.claude-3-haiku-20240307-v1:0 \
          --region us-east-1 \
          --body '{"inputText":"Hello, how are you?"}'
