name: Test AWS Bedrock Agent Connectivity

on:
  workflow_dispatch: # Allows you to manually trigger this workflow
  push:
    branches:
      - main
  pull_request:

env:
  AWS_REGION: us-east-1      

permissions:
  id-token: write
  contents: read

jobs:
  evaluate-agent:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        role-to-assume: ${{ vars.ACTION_EXECUTE_IAM_ROLE_ARN }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.AWS_REGION }}
        
    # Hello from AWS: WhoAmI
    - name: Sts GetCallerIdentity
      run: |
        aws sts get-caller-identity
    - name: Run Test Command
      run: |
        aws sts get-caller-identity # Verify credentials
        aws bedrock invoke-model \
          --model-id anthropic.claude-3-haiku-20240307-v1:0 \
          --region us-east-1 \
          --body '{"inputText":"Hello, how are you?"}'
