name: Test AWS Bedrock Agent

on:
  workflow_dispatch: # Allows you to manually trigger this workflow
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write  # Required for OIDC
  contents: read   # Required for actions/checkout

env:
  AWS_REGION: us-east-1 # Set your AWS region here (e.g., us-east-1)

jobs:
  evaluate-agent:
    runs-on: ubuntu-latest
    if: github.actor == 'professormeta' || github.actor == 'chrissandico' || github == 'cwang-dev'
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ vars.AWS_ROLE }}
        aws-region: ${{ vars.AWS_REGION }}

    # Hello from AWS: WhoAmI
    - name: Sts GetCallerIdentity
      run: |
        aws sts get-caller-identity

    - name: Set Up Python Virtual Environment
      run: |
        python3 -m venv .venv
        if [ ! -d ".venv" ]; then
          echo "Error: Virtual environment was not created successfully."
          exit 1
        fi

    - name: Activate Virtual Environment and Install Dependencies
      run: |
        source .venv/bin/activate
        pip install -r requirements.txt --upgrade
        pip install --upgrade pip setuptools wheel
        pip install agent-evaluation
        pip show agent-evaluation || { echo "Error: agent-evaluation installation failed."; exit 1; }

    - name: Test Bedrock Agent
      id: test-bedrock-agent
      env:
        BEDROCK_AGENT_ALIAS_ID: ${{ vars.BEDROCK_AGENT_ALIAS_ID }}
        BEDROCK_AGENT_ID: ${{ vars.BEDROCK_AGENT_ID }}
      run: |
        source .venv/bin/activate
        mkdir -p results/
        sed -e "s/BEDROCK_AGENT_ALIAS_ID/$BEDROCK_AGENT_ALIAS_ID/g" -e "s/BEDROCK_AGENT_ID/$BEDROCK_AGENT_ID/g" samples/test_plan_templates/bedrock_agent_target/template.yml > agenteval.yml
        agenteval run

#    - name: Upload Test Results
#      if: always()
#      uses: actions/upload-artifact@v3
#      with:
#        name: agent-evaluation-results
#        path: results/

#    - name: Append Test Summary to Job Summary
#      if: always()
#      run: |
#        if [ -f results/agenteval_summary.md ]; then
#          cat results/agenteval_summary.md >> $GITHUB_STEP_SUMMARY
#        fi
    - name: Test Summary
      if: always()
      id: test-summary
      run: |
        if [ -f agenteval_summary.md ]; then
          cat agenteval_summary.md >> $GITHUB_STEP_SUMMARY
        fi
